### ISSUE TITLE
Big Bug, Why the masks are misplaced？

### ISSUE THREAD

**Issue by zhouyang986** [rzamarefat/skinsegmenter#1]
Like your example image, the closer the masks is to the image boundary, the greater the deviation.

**Comment by zhouyang986** [comment]
Please modify to the following code To solve my problem :
        predskin = self._skin_model.predict(source=img, conf=self._skin_threshold, retina_masks = True, verbose=False)
        pred = self._seg_model.predict(source=img, conf=self._segmentation_confidence, retina_masks = True, verbose=False)

**Comment by rzamarefat** [comment]
Thank you for pointing it out. It is mnodified.

**Comment by zhouyang986** [comment]
My English is poor, what is "mnodified" ?

**Comment by zhouyang986** [comment]
i know , it is  modified  , meaning that it has been corrected，ok !
Thank you for such a good model ! thanks a lot !

**Comment by rzamarefat** [comment]
it was a spelling mistake. :))

**Comment by zhouyang986** [comment]
yeah～
